#!/bin/bash

[ "$1" = "0" ] && ( (killall onboard & killall firefox-bin & killall pcmanfm & killall evince & killall flameshot & killall alacritty); killall polybar;killall easystroke )
[ "$1" = "1" ] && (onboard & ~/.config/Configs/Scripts/taskete 1)
